package com.hfjy.service.order.dao;

import com.hfjy.service.order.model.OrderItem;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrderItemMapper {
    /**
     * 根据主键删除
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 新增
     *
     * @mbg.generated
     */
    int insert(OrderItem record);

    /**
     * 新增
     *
     * @mbg.generated
     */
    int insertSelective(OrderItem record);

    /**
     * 根据主键查找
     *
     * @mbg.generated
     */
    OrderItem selectByPrimaryKey(Long id);

    /**
     * 根据主键更新
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OrderItem record);

    List<OrderItem> getByOrderSn(@Param("orderSn") String orderSn);

    int batchInsert(List<OrderItem> items);
}