package com.hfjy.service.order.dao;

import com.hfjy.service.order.anno.DataSource;
import com.hfjy.service.order.model.Order;
import com.hfjy.service.order.wr.DataSourceType;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * 根据主键删除
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 新增
     *
     * @mbg.generated
     */
    int insert(Order record);

    /**
     * 新增
     *
     * @mbg.generated
     */
    int insertSelective(Order record);

    /**
     * 根据主键查找
     *
     * @mbg.generated
     */
    @DataSource(type = DataSourceType.READ, name = "slave2")
    Order selectByPrimaryKey(Long id);

    /**
     * 根据主键更新
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Order record);

    int updateStatusByPrimaryKey(@Param("id") Long id, @Param("status") Byte status);
}