package com.hfjy.service.order.dao;

import com.hfjy.service.order.model.Payment;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PaymentMapper {
    /**
     * 根据主键删除
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * 新增
     *
     * @mbg.generated
     */
    int insert(Payment record);

    /**
     * 新增
     *
     * @mbg.generated
     */
    int insertSelective(Payment record);

    /**
     * 根据主键查找
     *
     * @mbg.generated
     */
    Payment selectByPrimaryKey(Long id);

    /**
     * 根据主键更新
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Payment record);

    List<Payment> getByOrderSnAndStatus(@Param("orderSn")String orderSn, @Param("status")Integer status);

    int batchInsert(List<Payment> list);

    int updateStatusById(@Param("id") Long id,@Param("status") Integer status);
}