package com.hfjy.service.order.model;

import java.util.Date;

public class Payment {
    /**
     * id : 
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * order_sn : 订单编号
     *
     * @mbg.generated
     */
    private String orderSn;

    /**
     * status : 状态，1：待支付，2：待确认，3：成功，4：过期
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * pay_channel : 支付渠道
     *
     * @mbg.generated
     */
    private Byte payChannel;

    /**
     * source : 支付来源
     *
     * @mbg.generated
     */
    private Byte source;

    /**
     * pay_sum : 金额
     *
     * @mbg.generated
     */
    private Long paySum;

    /**
     * pay_time : 
     *
     * @mbg.generated
     */
    private Date payTime;

    /**
     * comment : 备注
     *
     * @mbg.generated
     */
    private String comment;

    /**
     * create_time : 创建时间
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * update_time : 更新时间
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * @return the value of payment.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     *
     * @param id the value for payment.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     *
     * @return the value of payment.order_sn
     *
     * @mbg.generated
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     *
     * @param orderSn the value for payment.order_sn
     *
     * @mbg.generated
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn == null ? null : orderSn.trim();
    }

    /**
     *
     * @return the value of payment.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     *
     * @param status the value for payment.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     *
     * @return the value of payment.pay_channel
     *
     * @mbg.generated
     */
    public Byte getPayChannel() {
        return payChannel;
    }

    /**
     *
     * @param payChannel the value for payment.pay_channel
     *
     * @mbg.generated
     */
    public void setPayChannel(Byte payChannel) {
        this.payChannel = payChannel;
    }

    /**
     *
     * @return the value of payment.source
     *
     * @mbg.generated
     */
    public Byte getSource() {
        return source;
    }

    /**
     *
     * @param source the value for payment.source
     *
     * @mbg.generated
     */
    public void setSource(Byte source) {
        this.source = source;
    }

    /**
     *
     * @return the value of payment.pay_sum
     *
     * @mbg.generated
     */
    public Long getPaySum() {
        return paySum;
    }

    /**
     *
     * @param paySum the value for payment.pay_sum
     *
     * @mbg.generated
     */
    public void setPaySum(Long paySum) {
        this.paySum = paySum;
    }

    /**
     *
     * @return the value of payment.pay_time
     *
     * @mbg.generated
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     *
     * @param payTime the value for payment.pay_time
     *
     * @mbg.generated
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     *
     * @return the value of payment.comment
     *
     * @mbg.generated
     */
    public String getComment() {
        return comment;
    }

    /**
     *
     * @param comment the value for payment.comment
     *
     * @mbg.generated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     *
     * @return the value of payment.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     *
     * @param createTime the value for payment.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     *
     * @return the value of payment.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     *
     * @param updateTime the value for payment.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", status=").append(status);
        sb.append(", payChannel=").append(payChannel);
        sb.append(", source=").append(source);
        sb.append(", paySum=").append(paySum);
        sb.append(", payTime=").append(payTime);
        sb.append(", comment=").append(comment);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append("]");
        return sb.toString();
    }
}