spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: liu1205
    hikari:
      maximum-pool-size: 50
      idle-timeout: 30000
server:
  port: 8000


